removing folders from .c9 before symlinking

diff --git a/files/opt/cs50/bin/docker-cmd b/files/opt/cs50/bin/docker-cmd
--- a/files/opt/cs50/bin/docker-cmd
+++ b/files/opt/cs50/bin/docker-cmd
@@ -1,9 +1,31 @@
 #!/bin/bash
 
-set -ex
+set -e
 
-sudo chown --recursive ubuntu:ubuntu /home/ubuntu && \
-    mkdir --parent /home/ubuntu/.c9 && \
-    ln --symbolic --force /opt/c9/* /home/ubuntu/.c9
+USER=$(whoami)
 
+echo "changing ownership of $HOME to $USER:$USER..."
+sudo chown --recursive "$USER:$USER" "$HOME"
+
+C9_FOLDER="/opt/c9"
+echo "c9 folder is $C9_FOLDER"
+
+USER_C9_FOLDER="$HOME/.c9"
+echo "user c9 folder is $USER_C9_FOLDER"
+
+echo "creating user c9 folder..."
+mkdir --parent "$USER_C9_FOLDER"
+
+# Remove c9 folders so that ln doesn't fail if they already exist
+C9_CONTENTS=$(find "$C9_FOLDER" -type d -mindepth 1 -maxdepth 1)
+for e in $C9_CONTENTS; do
+    e_="${e#$C9_FOLDER/}"
+    echo "removing $USER_C9_FOLDER/$e_..."
+    rm --force --recursive "$e_"
+done
+
+echo "symlinking $USER_C9_FOLDER to $C9_FOLDER/*..."
+ln --force --symbolic "$C9_FOLDER/*" "$USER_C9_FOLDER"
+
+echo "starting ssh..."
 sudo /usr/sbin/sshd -D
